defaults:
  # Look up the base file in env/office-world, naming the key as agent
  # This also makes the env/office-world the base directory for the env part of configuration (desirable)
#  - env/office-world@env: deliver_coffee
  - env/office-world@env: deliver_coffee
  - run: debugging_coffee_mail
  - algo: qrm
  - rm_learner: default
