num_observables: 2
seed: 123
buffer_size: 2000
policy_train_freq: 32
target_update_freq: 3000
er_start_size: 1000
er_sequence_length: 128
er_batch_size: 16
gamma: 0.99
optimizer_kws:
  lr: 1e-1
  rho: 0.8
lstm_hidden_state: 4
embedding_num_layers: 1
embedding_layer_size: 16
embedding_output_size: 4
use_double_dqn: True
use_gradient_clipping: False
exploration_rate_init: 1.0
exploration_rate_final: 0.1
exploration_rate_annealing_duration: 70000