training: True
total_episodes: 500
log_freq: 1
log_dir: logs
testing_freq: 250
greedy: True
recording_freq: 250
no_display: False
seed: 123
name: ??? # should make ???
extra_debug_information: True
only_log_base_metrics: False
num_envs: 10
# How often is the model stored
checkpoint_freq: 1000
# Should the trainer reload or always start training from scratch
restart_from_checkpoint: False

use_rs : True

